### ISSUE TITLE
chip-update-firmware.sh: S3 ETag does not match MD5 sum

### ISSUE THREAD

**Issue by rhencke** [NextThingCo/CHIP-tools#12]
For the PocketCHIP rootfs.ubi, the Amazon S3 ETag does not match the actual MD5 sum of the image.

This causes the `chip-update-firmware.sh` script to always re-download the image, even if the cached version is correct.

The S3 ETag is reported as b152646295eb74f40e36ef3baeae1c4d-10, but the md5sum is bf4a49b4f2fdf5817ea76c829bc4acf8.

**Comment by computermouth** [comment]
All images and scripts have been updated, please git pull CHIP-SDK and rerun setup script if the issue still persists.
