### ISSUE TITLE
Add 4.4 images support

### ISSUE THREAD

**Issue by hadess** [NextThingCo/CHIP-tools#13]
As mentioned in:
https://bbs.nextthing.co/t/chip-os-4-4-released-vga-hdmi-and-more/4319
CHIP-tools should be updated to allow installing the new versions. Not much of a fan of using a web browser to update firmwares...

**Comment by wcat13** [comment]
Agreed. Furthermore I cannot get flasher to work in the Chromium with elementary os.  Using this tool got me 4.3 headless. But I want 4.4.

Please tell me I am missing something?

**Comment by daurnimator** [comment]
(From link):

>  the format of the images is different and is why the CHIP-tools will no longer be able to flash this newest image. Users should expect an update to CHIP-tools soon that will support flashing the new image format.

Please release this! I've been so far unable to use the web flasher (not working for me on 3 different computers, running a mix of windows or linux). However I've been able to flash with CHIP-tools.

**Comment by daurnimator** [comment]
Ah ha! https://bbs.nextthing.co/t/flashing-upcoming-fixed-images-without-the-chrome-flasher/11304/5

@computermouth trying your branch now.

**Comment by tomchiverton** [comment]
Let's get this merged then

**Comment by computermouth** [comment]
https://github.com/NextThingCo/CHIP-tools/commit/902ae95a8a4352dfafbc84210d6c25e32d4f2265

Done! Sorry that took so long.
