### ISSUE TITLE
Flashing PocketCHIP image flashes the right ubifs, but possibly incorrect u-boot or dtb leading to no display.

### ISSUE THREAD

**Issue by aphlor** [NextThingCo/CHIP-tools#15]
Hi,

After using `chip-update-firmware.sh` with `-fp` to flash a PocketCHIP, the correct filesystem image is written to flash but either the dtb or u-boot image is incorrect. The display never illuminates, however connecting to the ttl uart gives a working console and examining the filesystem indicates that the PocketCHIP image has been correctly written.

Ordinarily, I'm not a Chrome user but I had to install it to use pcflash to reflash the CHIP with the correct binaries.

(Side note: It may be worthwhile indicating to users of `-p` that `-f` is also required due to the size of the ubifs exceeding available memory.)

Apologies, and thanks!

**Comment by computermouth** [comment]
Hi there,

All images and flashing scripts have since been updated. Please git pull your CHIP-SDK, and run the setup script before attempting to flash new images.
