### ISSUE TITLE
Possible bug in chip-update-firmware script.

### ISSUE THREAD

**Issue by OvaUbe** [NextThingCo/CHIP-tools#16]
Please pay attention to [this line](https://github.com/NextThingCo/CHIP-tools/blob/chip/stable/chip-update-firmware.sh#L89). I suppose it should be 

``` shell
FLASH_SCRIPT="./chip-fel-flash.sh -p"
```

because shell outputs "./chip-update-firmware.sh: line 89: -p: command not found" at this line.

**Comment by computermouth** [comment]
Sorry we never quite got around to the issue. The old flashing scripts are now deprecated, and as such, the problem is passively taken care of.
