### ISSUE TITLE
ubi flashing failure is reported as success

### ISSUE THREAD

**Issue by lastebil** [NextThingCo/CHIP-tools#17]
Line 173 of the chip-update-firmware (flash_images) does not check for success or failure, which causes ready_to_roll to always execute on line 175.

(4.4 multi branch.)

Additionally, common.sh flash_images does not appear to return an exit code, so the error can't be caught.

Resulting failure would very, very easily be seen as successful, as the ascii graphic and 'ready to roll' are much larger than the failure notice.

```
2016-11-13 21:38:12 (1.35 MB/s) - ‘chip-400000-4000.ubi.sparse’ saved [679477288/679477288]

Image Name:   flash gui
Created:      Sun Nov 13 21:38:12 2016
Image Type:   ARM Linux Script (uncompressed)
Data Size:    1758 Bytes = 1.72 kB = 0.00 MB
Load Address: 00000000
Entry Point:  00000000
Contents:
   Image 0: 1750 Bytes = 1.71 kB = 0.00 MB
waiting for fel...OK
waiting for fastboot.................................TIMEOUT
failed to flash the UBI image


FLASH VERIFICATION COMPLETE.
    


   #  #  #
  #########
###       ###
  # {#}   #
###  '%######
  #       #
###       ###
  ########
   #  #  #


    CHIP is ready to roll!

**Comment by computermouth** [comment]
I beefed up the error checking on the latest branch, thanks for reporting this, please try with the latest code in `chip/stable` branch.

-- Ben
