### ISSUE TITLE
libusb usb_bulk_send error -7

### ISSUE THREAD

**Issue by frostworx** [NextThingCo/CHIP-tools#2]
hi,
today I received my first alpha.
unfortunately I can't flash it though as I get tons of
"libusb usb_bulk_send error -7"
errors from fel
when running
chip-update-firmware.sh
tried different usb ports but this didn't help.
is my nand broken? should I run
BUILDROOT_OUTPUT_DIR=.firmware chip-fel.flash.sh erase-bb
don't want to kill it completely before having used it at least once.
# here's the complete output in case it helps (both CHIP-tools and sunxi-tools are at current master btw):

CHIP-tools # ./chip-update-firmware.sh 
BUILDROOT_OUTPUT_DIR = /usr/src/sources/2015/10/CHIP/CHIP-tools/.firmware
== preparing images ==
1+0 Datensätze ein
1+0 Datensätze aus
8192 Bytes (8,2 kB) kopiert, 0,000123345 s, 66,4 MB/s
1+0 Datensätze ein
1+0 Datensätze aus
8192 Bytes (8,2 kB) kopiert, 0,000647668 s, 12,6 MB/s
1+0 Datensätze ein
1+0 Datensätze aus
8192 Bytes (8,2 kB) kopiert, 0,00011479 s, 71,4 MB/s
1+0 Datensätze ein
1+0 Datensätze aus
8192 Bytes (8,2 kB) kopiert, 0,000629332 s, 13,0 MB/s
1+0 Datensätze ein
1+0 Datensätze aus
8192 Bytes (8,2 kB) kopiert, 0,00011472 s, 71,4 MB/s
1+0 Datensätze ein
1+0 Datensätze aus
8192 Bytes (8,2 kB) kopiert, 0,000642092 s, 12,8 MB/s
35+1 Datensätze ein
36+0 Datensätze aus
589824 Bytes (590 kB) kopiert, 0,000341767 s, 1,7 GB/s
12+0 Datensätze ein
12+0 Datensätze aus
196608 Bytes (197 kB) kopiert, 0,0124557 s, 15,8 MB/s
Image Name:   flash CHIP
Created:      Mon Oct  5 18:12:52 2015
Image Type:   ARM Linux Script (uncompressed)
Data Size:    856 Bytes = 0.84 kB = 0.00 MB
Load Address: 00000000
Entry Point:  00000000
Contents:
   Image 0: 848 Bytes = 0.83 kB = 0.00 MB
== upload the SPL to SRAM and execute it ==
libusb usb_bulk_send error -7
== upload images ==
libusb usb_bulk_send error -7
libusb usb_bulk_send error -7
libusb usb_bulk_send error -7
libusb usb_bulk_send error -7
== execute the main u-boot binary ==
# libusb usb_bulk_send error -7

same with a different usb cable

**Comment by kaplan2539** [comment]
Looks like your CHIP is not in FEL mode.

You can force it to FEL mode and try the flashing again by:
1. unplug CHIP from its powersource
2. connect the FEL pin (also known as UBOOT pin) to GND
3. power up CHIP again
4. run ./chip-update-firmware.sh again

You can find a photo showing how to connect the FEL pin to GND [here](https://nextthingco.zendesk.com/hc/en-us/articles/209757858-Flash-C-H-I-P-with-NTC-buildroot-Ubuntu-).

**Comment by frostworx** [comment]
unfortunately its not that easy.
I followed the instructions here: https://nextthingco.zendesk.com/hc/en-us/articles/209757858-Flash-C-H-I-P-with-NTC-buildroot-Ubuntu-
and the pins were set correctly. also tried multiple different pin cables, but they all fail with the -7 timeout.
is there any other way to force the fel mode?
lsusb lists the device like that:
1f3a:efe8 Onda (unverified) V972 tablet in flashing mode

**Comment by bbrezillon** [comment]
According to your message, it seems you're not launching the ./chip-update-firmware.sh script with root permissions. It that's the case, then launching the following command should solve the problem:

# sudo ./chip-update-firmware.sh

**Comment by frostworx** [comment]
nah, of course it is a root terminal. no need for sudo

**Comment by bbrezillon** [comment]
Could you paste the output of lsusb?

**Comment by bbrezillon** [comment]
Oh sorry, you already provided this information in your previous message.

**Comment by frostworx** [comment]
thanks for trying to help!
I pasted the lsusb part already above:
"1f3a:efe8 Onda (unverified) V972 tablet in flashing mode"

**Comment by bbrezillon** [comment]
Could you try to launch

$ fel version

(fel should be part of your buildroot build result)

**Comment by frostworx** [comment]
fel is part of the sunxi-tools here (followed above instructions).
# fel version
libusb usb_bulk_send error -7

the only fel in $PATH is /usr/local/bin/fel
which symlinks to the sunxi-tools git clone (current master).
already built fel with gcc 4.8.5 instead of 4.9.3 but no changes.
I'm running on ~amd64 gentoo btw

**Comment by bbrezillon** [comment]
Could you paste the output of lsmod?
Do you have an udev rule for 1f3a:efe8 USB device?

**Comment by frostworx** [comment]
I prefer to build all required drivers into the kernel, so lsmod just lists nvidia since years :}
I don't have a used rule for the device, but should it be even required for root?
if so, I think you found the problem

**Comment by frostworx** [comment]
hmm,
# fel version
AWUSBFEX soc=00001625(A13) 00000001 ver=0001 44 08 scratchpad=00007e00 00000000 00000000
works now, but the update still 
shows -7 errors.
a bit closer though, so thanks a lot, bbrezillon :}

**Comment by bbrezillon** [comment]
No, I was wondering if the device was not attached to a kernel driver, which could explain this failure, but since you don't have any udev-rules (and don't have the awusb driver loaded or statically compiled), I guess that's not the problem you're facing.

BTW, lsmod gives me the following output (as you can see there's no description of the device):
Bus 001 Device 008: ID 1f3a:efe8

**Comment by frostworx** [comment]
the lsusb description is part of a (often updated) package sys-apps/hwids.
probably you have some equivalent on your distribution.
some years ago there was some update-usbids program, but looks like it is dead

**Comment by frostworx** [comment]
"fel version" btw just works for the first X seconds. afterwards chip falls back to "-7".
haven't touched the chip for the last 2 days

**Comment by frostworx** [comment]
found this thread with a similar problem (I don't have usb reconnects though), but the problem in the thread fixed itself magically ( https://bbs.nextthing.co/t/libusb-error-timeout-archlinux-trying-to-flash/555 )
increasing the timeout and transferrate in fel as suggested in the thread didn't fix the timeouts.

would be nice if I could actually use the board for something useful, but imho it looks broken (tried several jumper cables, several usb cables, several pcs (all running gentoo)).
does the chip require some kernel driver which might be turned off?

**Comment by frostworx** [comment]
bought/tried another set of jumper cables (yeah, very small chance) but this didn't help too.
same btw in a virtualbox/vagrant setup, so obviously nothing is missing in my kernel.
so if there's no other way to force the board into fel mode I assume the board is simply broken...

**Comment by frostworx** [comment]
looks like a *wontfix*, but my 2nd alpha arrived some days ago and it works as it should.
so someone might want to close this issue

**Comment by adabsurdum** [comment]
Frostworx, your device probably isn't broken. I've had similar troubles with two alpha chips. On one of them the problem was intermittent; on the other it was constitutive. If you look in dmesg's log, you'll probably see  errors like:
 [16729.084811] xhci_hcd 0000:00:14.0: ERROR no room on ep ring
These are coming from the USB xhci_hcd driver (specifically the xhci-ring.c source) which, incidentally is chock full of FIXME comments. I'm going to work on fixing that tomorrow, but I was able to work around the problem by sticking a powered USB hub between the chip and my dev machine (a DLink DUB-H4). I'm guessing the problem is either 1) timing or 2) code paths, either or both of which are altered by sticking the hub in the middle. I'm going to follow up with the USB driver.

**Comment by frostworx** [comment]
thanks for your reply, adabsurdum!
I already started using a powered usb hub, then without, then the same on another machine.
currently I do not even have time for my working chip, but it is not urgent anyway.
