### ISSUE TITLE
Toshiba 4GB nand SLC

### ISSUE THREAD

**Issue by t-mon** [NextThingCo/CHIP-tools#25]
Hello! 
I'm trying to build the production image for our custom chip pro (guh GmbH) which has the Toshiba TC58TEG5DCLTA00 4GB flash and we want to use the flash as SLC. Your build scripts only provide the MLC configurations and I wanted to ask if you could provide us the parameters for the SLC configuration for building the ubifs image? 
Thanks in advance!

**Comment by t-mon** [comment]
Do I have to change something in the kernel dtb file to?

**Comment by computermouth** [comment]
Hi @t-mon,

For business requests and R&D, please forward all questions to your NTC sales representative. This way we'll be able to get back to you faster :)
